package factory;

import entity.ArrayEntity;
import exception.ArrayException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class EntityFactoryBuildingTest {
    private EntityFactoryBuilding factory;

    @BeforeEach
    void setUp() {
        factory = new EntityFactoryBuilding();
    }

    @Test
    @DisplayName("Should create entity with auto-generated id")
    void shouldCreateEntityWithAutoGeneratedId() throws ArrayException {
        int[] data = {1, 2, 3};

        ArrayEntity entity = factory.build(data, null);

        assertNotNull(entity);
        assertEquals(0L, entity.getId());
        assertArrayEquals(data, entity.getArray());
    }

    @Test
    @DisplayName("Should increment id for each created entity")
    void shouldIncrementIdForEachCreatedEntity() throws ArrayException {
        ArrayEntity entity1 = factory.build(new int[]{1}, null);
        ArrayEntity entity2 = factory.build(new int[]{2}, null);
        ArrayEntity entity3 = factory.build(new int[]{3}, null);

        assertEquals(0L, entity1.getId());
        assertEquals(1L, entity2.getId());
        assertEquals(2L, entity3.getId());
    }

    @Test
    @DisplayName("Should throw exception for null data")
    void shouldThrowExceptionForNullData() {
        assertThrows(ArrayException.class, () -> factory.build(null, null));
    }
}